name: ${REPO_NAME:?}-${PWD:?}

services:
  devcontainer:
    image: ghcr.io/dlrobson/${REPO_NAME}-ci:latest
    volumes:
      - ..:/workspaces/${REPO_NAME:?}:cached
    command: "bash -c 'trap exit TERM; sleep infinity & wait;'"
